// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlO8oPPeYrI4PSCMEWt_FQKXEjlACJkIg',
    appId: '1:753722068666:android:8fb526492ffc1f262a3c83',
    messagingSenderId: '753722068666',
    projectId: 'mast-1bcca',
    storageBucket: 'mast-1bcca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtuvwCz9QJvYiGGhfwPN35m2OMDQyZO6A',
    appId: '1:753722068666:ios:0e70e0c9f1daa6782a3c83',
    messagingSenderId: '753722068666',
    projectId: 'mast-1bcca',
    storageBucket: 'mast-1bcca.appspot.com',
    androidClientId: '753722068666-k9q29mqgrcfa8f841caarefdl33nhfa8.apps.googleusercontent.com',
    iosClientId: '753722068666-6e8h9pookml0t5a1cn7f2csorlcr95ik.apps.googleusercontent.com',
    iosBundleId: 'com.mast.da3m',
  );
}
